### ISSUE TITLE
Jwt secret should be configurable

### ISSUE THREAD

**Issue by osallou** [dinuti/dinuti#36]
Secret value should be configurable, from an env variable.
Using a default, if not defined, is ok for dev 

    app.use(session({ secret: 'dinuti',

**Comment by BlayFlorian** [comment]
Jwt secret is managed by express-jwt and passport. We must install [Helmet](https://github.com/helmetjs/helmet) to secure app by setting various HTTP headers.

**Comment by osallou** [comment]
Ok, thanks for clarification
