### ISSUE TITLE
[us-4-task-48] Create Button that update the  user_status (0,66 j/h) (5)

### ISSUE THREAD

**Issue by BzhTobal** [dinuti/dinuti#48]
- [x] AC-1 Refacto component location -> session
- [x] AC-2 Start the socket click button
- [x] AC-3 EventListener to add socket in home page
- [x] AC-4 Creation Service post Session

**Comment by BzhTobal** [comment]
Refacto component location -> session 
Start session when click Button

**Comment by BzhTobal** [comment]
Start the socket click button 
Creation Service post Session

**Comment by BlayFlorian** [comment]
@BlayFlorian 3
@KevinBoisgontier 1

RAE 1
